using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.GaussFabricator;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client._Moffstation.GaussFabricator;

[GenerateTypedNameReferences]
public sealed partial class GaussFabricatorWindow : FancyWindow
{
    [Dependency] private ILocalizationManager _loc = null!;

    public event Action<float>? OnAdjustDrawRate;
    public event Action<bool>? OnToggle;

    private const float TweenInverseHalfLife = 8f; // How the bar be moving

    private readonly ButtonGroup _toggleGroup = new();

    // Draw adjustment button increments, from smallest to largest
    private readonly IEnumerable<float> _increments = [1000f, 10000f, 50000f];

    private float _targetProgress;
    private float _displayedProgress;

    public GaussFabricatorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PopulateButtons();

        TemperatureBar.NoDataText = _loc.GetString("gauss-fabricator-window-no-data");
        PressureBar.NoDataText = _loc.GetString("gauss-fabricator-window-no-data");

        OnButton.Group = _toggleGroup;
        OffButton.Group = _toggleGroup;
        OnButton.OnPressed += _ => OnToggle?.Invoke(true);
        OffButton.OnPressed += _ => OnToggle?.Invoke(false);
    }

    public void UpdateState(GaussFabricatorBuiState state)
    {
        DrawRateLabel.Text = FormatPower(state.ConfiguredDrawRate);
        ReceivedLabel.Text = FormatPower(state.ReceivedPower);
        OutputRateLabel.Text = _loc.GetString(
            "gauss-fabricator-window-output-rate",
            ("rate", state.OutputRate.ToString("F2")));

        _targetProgress = Math.Clamp(state.Progress, 0f, 1f);

        DrawLevelBar.SetValues(state.MaxChargeRate, state.ReceivedPower, state.ConfiguredDrawRate);
        TemperatureBar.SetValue(state.Temperature);
        PressureBar.SetValue(state.Pressure);

        if (state.IsOn)
            OnButton.Pressed = true;
        else
            OffButton.Pressed = true;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var factor = MathHelper.Clamp01(TweenInverseHalfLife * args.DeltaSeconds);
        _displayedProgress = MathHelper.Lerp(_displayedProgress, _targetProgress, factor);

        if (MathF.Abs(_displayedProgress - _targetProgress) < 0.001f)
            _displayedProgress = _targetProgress;

        OutputProgressBar.Value = _displayedProgress;
        OutputProgressBar.ForegroundStyleBoxOverride = new StyleBoxFlat(ProgressColor(_displayedProgress));
    }

    private void PopulateButtons()
    {
        AdjustmentButtons.Children.Clear();

        AdjustmentButtons.AddChild(BuildRow(_increments.Select(i => -i)));
        AdjustmentButtons.AddChild(BuildRow(_increments));
    }

    private BoxContainer BuildRow(IEnumerable<float> increments)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        var deltas = increments.ToList();
        for (var i = 0; i < deltas.Count; i++)
        {
            var delta = deltas[i];
            // if its less than zero add a negative sign, if its positive add a plus sign
            // Doing this because FormatPower doesn't support negative numbers
            var button = new Button { Text = (delta < 0 ? "-" : "+") + FormatPower(Math.Abs(delta)), HorizontalExpand = true };

            if (i == 0)
                button.StyleClasses.Add("OpenRight");
            else if (i == deltas.Count - 1)
                button.StyleClasses.Add("OpenLeft");
            else
                button.StyleClasses.Add("OpenBoth");

            button.OnPressed += _ => OnAdjustDrawRate?.Invoke(delta);
            row.AddChild(button);
        }

        return row;
    }

    private static Color ProgressColor(float t)
    {
        return t < 0.5f
            ? Color.InterpolateBetween(Color.Red, Color.Lime, t * 2f)
            : Color.InterpolateBetween(Color.Lime, Color.Cyan, (t - 0.5f) * 2f);
    }

    private string FormatPower(float value)
    {
        return _loc.GetString("battery-menu-power-value", ("value", value));
    }
}
