using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.GaussFabricator;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client._Moffstation.GaussFabricator;

[GenerateTypedNameReferences]
public sealed partial class GaussFabricatorWindow : FancyWindow
{
    [Dependency] private ILocalizationManager _loc = null!;

    public event Action<float>? OnAdjustDrawRate;
    public event Action<bool>? OnToggle;

    private readonly ButtonGroup _toggleGroup = new();

    // Draw adjustment button increments, from largest to smallest
    private readonly IEnumerable<float> _increments = [50000f, 10000f, 1000f];

    private float _targetProgress;
    private float _displayedProgress;

    public GaussFabricatorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PopulateButtons();

        OnButton.Group = _toggleGroup;
        OffButton.Group = _toggleGroup;
        OnButton.OnPressed += _ => OnToggle?.Invoke(true);
        OffButton.OnPressed += _ => OnToggle?.Invoke(false);
    }

    public void UpdateState(GaussFabricatorBuiState state)
    {
        DrawRateLabel.Text = FormatPower(state.ConfiguredDrawRate);
        ReceivedLabel.Text = FormatPower(state.ReceivedPower);

        _targetProgress = Math.Clamp(state.Progress, 0f, 1f);

        DrawLevelBar.SetValues(state.MaxChargeRate, state.ReceivedPower, state.ConfiguredDrawRate);

        if (state.IsOn)
            OnButton.Pressed = true;
        else
            OffButton.Pressed = true;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        const float tweenInverseHalfLife = 8f;
        var factor = MathHelper.Clamp01(tweenInverseHalfLife * args.DeltaSeconds);
        _displayedProgress = MathHelper.Lerp(_displayedProgress, _targetProgress, factor);

        if (MathF.Abs(_displayedProgress - _targetProgress) < 0.001f)
            _displayedProgress = _targetProgress;

        OutputProgressBar.Value = _displayedProgress;
        OutputProgressBar.ForegroundStyleBoxOverride = new StyleBoxFlat(ProgressColor(_displayedProgress));
    }

    private void PopulateButtons()
    {
        AdjustmentButtons.Children.Clear();
        var deltas = _increments.Select(i => -i).Concat(_increments.Reverse()).ToList();
        AdjustmentButtons.Columns = deltas.Count;
        for (var i = 0; i < deltas.Count; i++)
        {
            var delta = deltas[i];
            // if its less than zero add a negative sign, if its positive don't
            // Doing this because FormatPower doesn't support negative numbers
            var button = new Button { Text = (delta < 0 ? "-" : "") + FormatPower(Math.Abs(delta)), HorizontalExpand = true };

            // Setup the style classes
            if (i == 0)
                button.StyleClasses.Add("OpenRight");
            else if (i == deltas.Count - 1)
                button.StyleClasses.Add("OpenLeft");
            else
                button.StyleClasses.Add("OpenBoth");

            button.OnPressed += _ => OnAdjustDrawRate?.Invoke(delta);
            AdjustmentButtons.AddChild(button);
        }
    }

    private static Color ProgressColor(float t)
    {
        if (t < 0.5f)
            return Color.InterpolateBetween(Color.Red, Color.Lime, t * 2f);

        return Color.InterpolateBetween(Color.Lime, Color.Cyan, (t - 0.5f) * 2f);
    }

    private string FormatPower(float value)
    {
        return _loc.GetString("battery-menu-power-value", ("value", value));
    }
}
