using System.Linq;
using Content.Shared._Moffstation.Preferences.Loadouts;
using Content.Shared.Clothing;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Preferences.Loadouts.Effects;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.Lobby.UI.Loadouts;

/// <summary>
/// Browses one role loadout at a time as a grid of item cards. The Universal scope is offered alongside every job
/// that has a loadout, and a job group that has selections marks the matching Universal group as overridden.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MoffLoadoutEditor : BoxContainer
{
    private const int GridColumns = 5;

    private static readonly Color LimitReachedColor = Color.FromHex("#ff555d");
    private static readonly Color MutedColor = Color.FromHex("#9eabb5");

    [Dependency] private IPrototypeManager _prototypeManager = null!;
    [Dependency] private IPlayerManager _playerManager = null!;
    [Dependency] private IEntityManager _entityManager = null!;

    private readonly List<LoadoutScope> _scopes = new();
    private readonly LoadoutSystem _loadoutSystem;

    private HumanoidCharacterProfile? _profile;
    private LoadoutScope? _selectedScope;
    private RoleLoadout? _selectedLoadout;
    private RoleLoadoutPrototype? _selectedRolePrototype;
    private ProtoId<LoadoutGroupPrototype>? _selectedGroup;
    private bool _suppressScopeSelection;

    public event Action<HumanoidCharacterProfile>? ProfileChanged;
    public event Action<JobPrototype?>? PreviewJobChanged;

    public MoffLoadoutEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _loadoutSystem = _entityManager.System<LoadoutSystem>();

        ScopeSelector.OnItemSelected += args =>
        {
            if (_suppressScopeSelection)
                return;

            ScopeSelector.SelectId(args.Id);
            SelectScope(args.Id);
        };

        SearchEdit.OnTextChanged += _ =>
        {
            ClearSearchButton.Disabled = string.IsNullOrEmpty(SearchEdit.Text);
            RefreshCatalog();
        };

        ClearSearchButton.OnPressed += _ =>
        {
            SearchEdit.Text = string.Empty;
            ClearSearchButton.Disabled = true;
            RefreshCatalog();
        };

        SelectedOnly.OnToggled += _ => RefreshCatalog();
        ResetCategoryButton.OnPressed += _ => ResetCurrentCategory();
        ResetLoadoutButton.OnPressed += _ => ResetCurrentLoadout();
    }

    public void SetProfile(HumanoidCharacterProfile? profile)
    {
        var previousRole = _selectedScope?.RoleId;

        _profile = profile;
        _selectedScope = null;
        _selectedLoadout = null;
        _selectedRolePrototype = null;
        _selectedGroup = null;

        UpdateCategoryHeader(null);
        RebuildScopes(previousRole);
    }

    /// <summary>Updates the profile without rebuilding, for changes made elsewhere in the editor.</summary>
    public void SyncProfile(HumanoidCharacterProfile? profile)
    {
        _profile = profile;
    }

    public void SelectJob(string jobId)
    {
        var roleId = LoadoutSystem.GetJobPrototype(jobId);
        var index = _scopes.FindIndex(scope => scope.RoleId == roleId);

        if (index < 0)
            return;

        _suppressScopeSelection = true;
        ScopeSelector.SelectId(index);
        _suppressScopeSelection = false;

        SelectScope(index);
    }

    private void RebuildScopes(string? previousRole)
    {
        _scopes.Clear();
        ScopeSelector.Clear();

        if (_profile == null)
        {
            ClearEditor();
            return;
        }

        if (_prototypeManager.HasIndex(MoffLoadouts.Universal))
            _scopes.Add(new LoadoutScope(Loc.GetString("moff-loadout-scope-universal"), MoffLoadouts.Universal, null));

        var jobs = _prototypeManager.EnumeratePrototypes<JobPrototype>()
            .Where(job => job.SetPreference)
            .OrderBy(job => job.LocalizedName);

        foreach (var job in jobs)
        {
            var roleId = LoadoutSystem.GetJobPrototype(job.ID);

            if (!_prototypeManager.TryIndex<RoleLoadoutPrototype>(roleId, out var rolePrototype))
                continue;

            if (rolePrototype.Groups.Count == 0)
                continue;

            _scopes.Add(new LoadoutScope(job.LocalizedName, roleId, job));
        }

        for (var i = 0; i < _scopes.Count; i++)
        {
            ScopeSelector.AddItem(GetScopeDisplayName(_scopes[i]), i);
        }

        if (_scopes.Count == 0)
        {
            ClearEditor();
            return;
        }

        var selectedIndex = previousRole == null
            ? -1
            : _scopes.FindIndex(scope => scope.RoleId == previousRole);

        if (selectedIndex < 0)
            selectedIndex = 0;

        _suppressScopeSelection = true;
        ScopeSelector.SelectId(selectedIndex);
        _suppressScopeSelection = false;

        SelectScope(selectedIndex);
    }

    private void SelectScope(int index)
    {
        if (_profile == null ||
            _playerManager.LocalSession is not { } session ||
            IoCManager.Instance is not { } collection ||
            index < 0 ||
            index >= _scopes.Count)
        {
            return;
        }

        _selectedScope = _scopes[index];

        if (!_prototypeManager.TryIndex<RoleLoadoutPrototype>(_selectedScope.RoleId, out var rolePrototype))
        {
            ClearEditor();
            return;
        }

        _selectedRolePrototype = rolePrototype;

        _selectedLoadout = _profile.Loadouts.TryGetValue(_selectedScope.RoleId, out var savedLoadout)
            ? savedLoadout.Clone()
            : new RoleLoadout(rolePrototype.ID);

        _selectedLoadout.SetDefault(_profile, session, _prototypeManager);
        _selectedLoadout.EnsureValid(_profile, session, collection);

        _selectedGroup = null;

        RefreshCategories();
        RefreshPoints();
        RefreshCatalog();

        PreviewJobChanged?.Invoke(_selectedScope.Job);
    }

    /// <summary>
    /// Upstream group names are prefixed with their job name, which is redundant once the job is the selected scope.
    /// </summary>
    private string GetGroupDisplayName(LoadoutGroupPrototype groupPrototype)
    {
        var name = Loc.GetString(groupPrototype.Name);
        var jobName = _selectedScope?.Job?.LocalizedName;

        if (!string.IsNullOrWhiteSpace(jobName))
        {
            var prefix = jobName + " ";

            if (name.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                name = name[prefix.Length..];
        }

        if (name.Length > 0)
            name = string.Concat(char.ToUpperInvariant(name[0]), name.AsSpan(1).ToString());

        return name;
    }

    private void UpdateCategoryHeader(ProtoId<LoadoutGroupPrototype>? group)
    {
        ResetCategoryButton.Disabled = group == null;

        if (group is not { } groupId ||
            !_prototypeManager.TryIndex<LoadoutGroupPrototype>(groupId, out var groupPrototype))
        {
            CategoryTitle.Text = Loc.GetString("moff-loadout-all-items");
            CategoryRequirementLabel.Text = string.Empty;
            CategoryRequirementLabel.Visible = false;
            return;
        }

        CategoryTitle.Text = GetGroupDisplayName(groupPrototype);

        if (IsUniversalOverride(groupId))
            CategoryTitle.Text += " *";

        var selectedCount = 0;

        if (_selectedLoadout != null && _selectedLoadout.SelectedLoadouts.TryGetValue(groupId, out var selected))
            selectedCount = selected.Count;

        var minimum = groupPrototype.MinLimit;
        var maximum = groupPrototype.MaxLimit;

        CategoryRequirementLabel.Modulate = maximum > 0 && selectedCount >= maximum
            ? LimitReachedColor
            : MutedColor;

        CategoryRequirementLabel.Text = minimum switch
        {
            1 => Loc.GetString("moff-loadout-category-required"),
            > 1 => Loc.GetString("moff-loadout-category-requires",
                ("required", minimum),
                ("selected", selectedCount)),
            _ when maximum > 0 => Loc.GetString("moff-loadout-category-selected-max",
                ("selected", selectedCount),
                ("max", maximum)),
            _ when selectedCount > 0 => Loc.GetString("moff-loadout-category-selected", ("selected", selectedCount)),
            _ => Loc.GetString("moff-loadout-category-optional"),
        };

        CategoryRequirementLabel.Visible = true;
    }

    private void RefreshCategories()
    {
        CategoryList.RemoveAllChildren();

        if (_selectedRolePrototype == null || _selectedLoadout == null)
            return;

        AddCategoryButton(Loc.GetString("moff-loadout-all-items"), null);

        foreach (var groupId in _selectedRolePrototype.Groups)
        {
            if (!_prototypeManager.TryIndex(groupId, out var groupPrototype))
                continue;

            if (groupPrototype.Hidden)
                continue;

            var name = GetGroupDisplayName(groupPrototype);

            if (IsUniversalOverride(groupId))
                name += " *";

            AddCategoryButton(name, groupId);
        }
    }

    private void AddCategoryButton(string name, ProtoId<LoadoutGroupPrototype>? group)
    {
        var button = new Button
        {
            Text = name,
            ToggleMode = true,
            Pressed = Nullable.Equals(_selectedGroup, group),
            HorizontalExpand = true,
        };

        button.OnPressed += _ =>
        {
            _selectedGroup = group;

            UpdateCategoryHeader(group);
            RefreshCategories();
            RefreshCatalog();
        };

        CategoryList.AddChild(button);
    }

    private void RefreshCatalog()
    {
        ItemGrid.RemoveAllChildren();

        if (_profile == null ||
            _selectedLoadout == null ||
            _selectedRolePrototype == null ||
            _playerManager.LocalSession is not { } session ||
            IoCManager.Instance is not { } collection)
        {
            return;
        }

        var search = SearchEdit.Text.Trim();
        var displayed = 0;
        var cardMinimumWidth = 0f;
        var showCost = _selectedRolePrototype.Points != null;

        foreach (var entry in GetCatalogEntries())
        {
            var itemName = _loadoutSystem.GetName(entry.Prototype);

            if (string.IsNullOrWhiteSpace(itemName))
                itemName = entry.Prototype.ID;

            var selected = IsSelected(entry.Group, entry.Prototype.ID);

            if (SelectedOnly.Pressed && !selected)
                continue;

            if (search.Length > 0 && !itemName.Contains(search, StringComparison.OrdinalIgnoreCase))
                continue;

            FormattedMessage? reason = null;
            var valid = true;

            // Already-selected items must stay clickable so they can be deselected.
            if (!selected)
                valid = _selectedLoadout.IsValid(_profile, session, entry.Prototype.ID, collection, out reason);

            var cost = entry.Prototype.Effects.OfType<PointsCostLoadoutEffect>().Sum(effect => effect.Cost);

            var card = new MoffLoadoutItemCard();
            cardMinimumWidth = card.MinWidth;

            card.Configure(entry.Prototype, itemName, cost, showCost, selected, !valid, reason);

            card.SelectionChanged += pressed =>
            {
                if (_selectedLoadout == null)
                    return;

                var changed = pressed
                    ? _selectedLoadout.AddLoadout(entry.Group, entry.Prototype.ID, _prototypeManager)
                    : _selectedLoadout.RemoveLoadout(entry.Group, entry.Prototype.ID, _prototypeManager);

                if (changed)
                    CommitSelection();
            };

            ItemGrid.AddChild(card);
            displayed++;
        }

        // Pad the last row so the final card doesn't stretch across the grid.
        var remainder = displayed % GridColumns;

        if (remainder > 0)
        {
            for (var i = remainder; i < GridColumns; i++)
            {
                ItemGrid.AddChild(new Control
                {
                    HorizontalExpand = true,
                    MinWidth = cardMinimumWidth,
                });
            }
        }
    }

    private List<CatalogEntry> GetCatalogEntries()
    {
        var result = new List<CatalogEntry>();
        var seen = new HashSet<string>();

        if (_selectedRolePrototype == null)
            return result;

        foreach (var groupId in _selectedRolePrototype.Groups)
        {
            if (_selectedGroup is { } selectedGroup && groupId != selectedGroup)
                continue;

            if (!_prototypeManager.TryIndex(groupId, out var groupPrototype))
                continue;

            if (groupPrototype.Hidden)
                continue;

            foreach (var loadoutId in groupPrototype.Loadouts)
            {
                if (!seen.Add(loadoutId))
                    continue;

                if (!_prototypeManager.TryIndex(loadoutId, out var loadoutPrototype))
                    continue;

                result.Add(new CatalogEntry(groupId, loadoutPrototype));
            }
        }

        return result.OrderBy(entry => _loadoutSystem.GetName(entry.Prototype)).ToList();
    }

    private bool IsSelected(ProtoId<LoadoutGroupPrototype> group, ProtoId<LoadoutPrototype> loadout)
    {
        if (_selectedLoadout == null || !_selectedLoadout.SelectedLoadouts.TryGetValue(group, out var selected))
            return false;

        return selected.Any(item => item.Prototype == loadout);
    }

    private void ResetCurrentCategory()
    {
        if (_profile == null ||
            _selectedLoadout == null ||
            _selectedGroup is not { } groupId ||
            _playerManager.LocalSession is not { } session)
        {
            return;
        }

        _selectedLoadout.SelectedLoadouts.Remove(groupId);
        _selectedLoadout.SetDefault(_profile, session, _prototypeManager);

        CommitSelection();
    }

    private void ResetCurrentLoadout()
    {
        if (_profile == null ||
            _selectedRolePrototype == null ||
            _playerManager.LocalSession is not { } session)
        {
            return;
        }

        _selectedLoadout = new RoleLoadout(_selectedRolePrototype.ID);
        _selectedLoadout.SetDefault(_profile, session, _prototypeManager);

        CommitSelection();
    }

    private void CommitSelection()
    {
        if (_profile == null ||
            _selectedLoadout == null ||
            _playerManager.LocalSession is not { } session ||
            IoCManager.Instance is not { } collection)
        {
            return;
        }

        _selectedLoadout.EnsureValid(_profile, session, collection);

        _profile = _profile.WithLoadout(_selectedLoadout);

        RefreshScopeMarker();
        RefreshPoints();
        ProfileChanged?.Invoke(_profile);

        // Avoid disposing the clicked card while its input event is still running.
        UserInterfaceManager.DeferAction(() =>
        {
            RefreshCategories();
            UpdateCategoryHeader(_selectedGroup);
            RefreshCatalog();
        });
    }

    private void RefreshPoints()
    {
        if (_selectedRolePrototype == null ||
            _selectedLoadout == null ||
            _selectedRolePrototype.Points is not { } maximum)
        {
            PointLabel.Text = string.Empty;
            PointLabel.Visible = false;
            PointBar.Visible = false;
            return;
        }

        var remaining = _selectedLoadout.Points ?? maximum;
        var used = Math.Max(0, maximum - remaining);

        PointLabel.Visible = true;
        PointLabel.Modulate = maximum > 0 && used >= maximum ? LimitReachedColor : MutedColor;
        PointLabel.Text = Loc.GetString("moff-loadout-points", ("used", used), ("max", maximum));

        PointBar.Visible = true;
        PointBar.MinValue = 0;
        PointBar.MaxValue = Math.Max(1, maximum);
        PointBar.Value = used;
    }

    private void ClearEditor()
    {
        CategoryList.RemoveAllChildren();
        ItemGrid.RemoveAllChildren();

        PointLabel.Text = string.Empty;
        PointLabel.Visible = false;
        PointBar.Visible = false;

        PreviewJobChanged?.Invoke(null);
    }

    private bool HasConfiguredLoadout(string roleId)
    {
        if (_profile == null || !_profile.Loadouts.TryGetValue(roleId, out var loadout))
            return false;

        return loadout.SelectedLoadouts.Any(group => group.Value.Count > 0);
    }

    /// <summary>
    /// Whether the currently selected job group displaces the Universal loadout's version of that group, matching
    /// what <c>StationSpawningSystem</c> does at spawn.
    /// </summary>
    private bool IsUniversalOverride(ProtoId<LoadoutGroupPrototype> groupId)
    {
        // Universal cannot override itself.
        if (_selectedScope?.Job == null || _selectedLoadout == null)
            return false;

        if (!_prototypeManager.TryIndex(MoffLoadouts.Universal, out var universalPrototype) ||
            !universalPrototype.Groups.Contains(groupId))
        {
            return false;
        }

        return _selectedLoadout.SelectedLoadouts.TryGetValue(groupId, out var selected) && selected.Count > 0;
    }

    private string GetScopeDisplayName(LoadoutScope scope)
    {
        return scope.Job != null && HasConfiguredLoadout(scope.RoleId)
            ? scope.Name + " *"
            : scope.Name;
    }

    private void RefreshScopeMarker()
    {
        if (_selectedScope == null)
            return;

        var index = _scopes.FindIndex(scope => scope.RoleId == _selectedScope.RoleId);

        if (index < 0)
            return;

        ScopeSelector.SetItemText(index, GetScopeDisplayName(_scopes[index]));
    }

    private sealed record LoadoutScope(string Name, string RoleId, JobPrototype? Job);

    private sealed record CatalogEntry(ProtoId<LoadoutGroupPrototype> Group, LoadoutPrototype Prototype);
}
