using Content.Shared.Clothing;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.Lobby.UI.Loadouts;

/// <summary>
/// One selectable item in the loadout editor, showing its name, point cost and a sprite preview.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MoffLoadoutItemCard : ContainerButton
{
    private const int MaximumDisplayedNameLength = 24;

    [Dependency] private IEntityManager _entityManager = null!;

    private EntityUid? _previewEntity;
    private bool _suppressSelectionEvent;

    public event Action<bool>? SelectionChanged;

    public MoffLoadoutItemCard()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        OnToggled += args =>
        {
            if (_suppressSelectionEvent)
                return;

            SelectionChanged?.Invoke(args.Pressed);
        };
    }

    public void Configure(
        LoadoutPrototype prototype,
        string name,
        int cost,
        bool showCost,
        bool selected,
        bool disabled,
        FormattedMessage? disabledReason)
    {
        // Plenty of loadout names are far too long for a card, so keep the full one on the tooltip.
        ItemNameLabel.Text = name.Length <= MaximumDisplayedNameLength
            ? name
            : name[..(MaximumDisplayedNameLength - 1)].TrimEnd() + "…";

        ItemNameLabel.ToolTip = name;
        CostLabel.Text = cost.ToString();
        CostLabel.Visible = showCost;

        SetSelected(selected);
        Disabled = disabled;

        var loadoutSystem = _entityManager.System<LoadoutSystem>();
        var entityPrototype = prototype.DummyEntity ?? loadoutSystem.GetFirstOrNull(prototype);

        if (entityPrototype != null)
        {
            var previewEntity = _entityManager.SpawnEntity(entityPrototype, MapCoordinates.Nullspace);

            _previewEntity = previewEntity;
            ItemSprite.SetEntity(previewEntity);

            if (_entityManager.TryGetComponent<MetaDataComponent>(previewEntity, out var metadata))
                ToolTip = metadata.EntityDescription;
        }

        if (disabled && disabledReason != null)
        {
            var tooltip = new Tooltip();
            tooltip.SetMessage(disabledReason);
            TooltipSupplier = _ => tooltip;
        }
    }

    public void SetSelected(bool selected)
    {
        _suppressSelectionEvent = true;
        Pressed = selected;
        _suppressSelectionEvent = false;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        ItemSprite.SetEntity(null);
        _entityManager.TryQueueDeleteEntity(_previewEntity);
        _previewEntity = null;
    }
}
