using System.Linq;
using Content.Client.Lobby.UI;
using Content.Client.Players.PlayTimeTracking;
using Content.Shared.Clothing;
using Content.Shared.GameTicking;
using Content.Shared.Guidebook;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Moffstation.Lobby.UI.Roles;

/// <summary>
/// The Roles tab: jobs as searchable, department-grouped cards, plus the fork's antag tab alongside them.
/// A card's toggle only records whether the character will take the job — the priority itself is player-global
/// and lives in <c>MoffJobPriorityEditor</c>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MoffRolesEditor : BoxContainer
{
    private const int JobColumns = 2;
    private const int ChipColumns = 4;

    private static readonly Color MutedColor = Color.FromHex("#9aa8b2");

    [Dependency] private IPrototypeManager _prototypeManager = null!;
    [Dependency] private IEntityManager _entityManager = null!;
    [Dependency] private JobRequirementsManager _requirements = null!;

    /// <summary>
    /// Maps each department-filter option to its prototype ID. A null entry is the unfiltered "all departments".
    /// </summary>
    private readonly List<string?> _jobDepartmentFilters = new();

    private readonly SpriteSystem _sprite;

    private HumanoidCharacterProfile? _profile;
    private string? _selectedJobDepartment;

    /// <summary>Raised whenever a job or preference change produces a new character profile.</summary>
    public event Action<HumanoidCharacterProfile>? ProfileChanged;

    /// <summary>Raised when the player asks for the loadout editor for a particular job.</summary>
    public event Action<JobPrototype>? LoadoutRequested;

    /// <summary>Raised when the preview should show a particular job's clothing.</summary>
    public event Action<JobPrototype?>? PreviewJobChanged;

    /// <summary>Raised when the player asks to open a job's guidebook entries.</summary>
    public event Action<List<ProtoId<GuideEntryPrototype>>>? OpenGuidebookRequested;

    public MoffRolesEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entityManager.System<SpriteSystem>();

        RolesTabContainer.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-jobs-tab"));
        RolesTabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-antags-tab"));

        PreferenceUnavailableButton.AddItem(
            Loc.GetString("moff-roles-unavailable-stay"),
            (int) PreferenceUnavailableMode.StayInLobby);

        PreferenceUnavailableButton.AddItem(
            Loc.GetString("moff-roles-unavailable-overflow",
                ("overflowJob", Loc.GetString(SharedGameTicker.FallbackOverflowJobName))),
            (int) PreferenceUnavailableMode.SpawnAsOverflow);

        PreferenceUnavailableButton.OnItemSelected += args =>
        {
            PreferenceUnavailableButton.SelectId(args.Id);

            if (_profile == null)
                return;

            _profile = _profile.WithPreferenceUnavailable((PreferenceUnavailableMode) args.Id);
            NotifyProfileChanged();
        };

        EnabledJobsHeader.OnPressed += _ =>
        {
            EnabledJobsPanel.Visible = !EnabledJobsPanel.Visible;
            EnabledJobsChevron.Text = EnabledJobsPanel.Visible ? "▼" : "▶";
        };

        JobSearch.OnTextChanged += _ =>
        {
            JobSearchClearButton.Disabled = string.IsNullOrEmpty(JobSearch.Text);
            RefreshJobs();
        };

        JobSearchClearButton.OnPressed += _ =>
        {
            JobSearch.Text = string.Empty;
            JobSearchClearButton.Disabled = true;
            RefreshJobs();
        };

        JobDepartmentFilter.OnItemSelected += args =>
        {
            JobDepartmentFilter.SelectId(args.Id);

            _selectedJobDepartment = args.Id >= 0 && args.Id < _jobDepartmentFilters.Count
                ? _jobDepartmentFilters[args.Id]
                : null;

            RefreshJobs();
        };

        JobSelectedOnly.OnToggled += _ => RefreshJobs();
    }

    public void SetProfile(HumanoidCharacterProfile? profile)
    {
        SyncProfile(profile);
        RefreshJobs();
    }

    /// <summary>Updates the profile without rebuilding, for changes made elsewhere in the editor.</summary>
    public void SyncProfile(HumanoidCharacterProfile? profile)
    {
        _profile = profile;
    }

    public void RefreshJobs()
    {
        JobList.RemoveAllChildren();
        EnabledJobsList.RemoveAllChildren();

        var departments = _prototypeManager.EnumeratePrototypes<DepartmentPrototype>()
            .Where(department => !department.EditorHidden)
            .ToList();

        // Preserve upstream department ordering, including command positions.
        departments.Sort(DepartmentUIComparer.Instance);

        var jobDepartments = BuildJobDepartmentMap(departments);

        var jobs = _prototypeManager.EnumeratePrototypes<JobPrototype>()
            .Where(job => job.SetPreference && jobDepartments.ContainsKey(job.ID))
            .OrderBy(job => job.LocalizedName)
            .ToList();

        SetupDepartmentFilter(departments);

        bool IsEnabled(JobPrototype job) =>
            MoffJobPreference.IsEnabled(_profile?.JobPriorities.GetValueOrDefault(job.ID, JobPriority.Never)
                                        ?? JobPriority.Never);

        RefreshEnabledJobs(jobs, IsEnabled);

        var search = JobSearch.Text.Trim();

        var filtered = jobs.Where(job =>
        {
            if (JobSelectedOnly.Pressed && !IsEnabled(job))
                return false;

            if (_selectedJobDepartment != null && !jobDepartments[job.ID].Contains(_selectedJobDepartment))
                return false;

            if (search.Length == 0)
                return true;

            return job.LocalizedName.Contains(search, StringComparison.OrdinalIgnoreCase) ||
                   (job.LocalizedDescription?.Contains(search, StringComparison.OrdinalIgnoreCase) ?? false);
        }).ToList();

        if (filtered.Count == 0)
        {
            JobList.AddChild(new Label
            {
                Text = Loc.GetString("moff-roles-no-jobs-match"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(8),
            });

            return;
        }

        foreach (var department in departments)
        {
            if (_selectedJobDepartment != null && department.ID != _selectedJobDepartment)
                continue;

            // Heads of staff belong to Command as well as their own department; only list them under one.
            var departmentJobs = filtered
                .Where(job => department.Roles.Contains(job.ID) && (department.Primary || department.ID == "Command"))
                .OrderBy(job => job, JobUIComparer.Instance)
                .ToList();

            if (departmentJobs.Count == 0)
                continue;

            AddDepartmentHeader(department);
            AddDepartmentJobs(departmentJobs, IsEnabled);
        }
    }

    /// <summary>A job can belong to more than one department, so track the whole set for filtering.</summary>
    private static Dictionary<string, HashSet<string>> BuildJobDepartmentMap(List<DepartmentPrototype> departments)
    {
        var result = new Dictionary<string, HashSet<string>>();

        foreach (var department in departments)
        {
            foreach (var jobId in department.Roles)
            {
                if (!result.TryGetValue(jobId, out var jobDepartmentSet))
                {
                    jobDepartmentSet = new HashSet<string>();
                    result[jobId] = jobDepartmentSet;
                }

                jobDepartmentSet.Add(department.ID);
            }
        }

        return result;
    }

    private void SetupDepartmentFilter(List<DepartmentPrototype> departments)
    {
        if (_jobDepartmentFilters.Count != 0)
            return;

        JobDepartmentFilter.Clear();

        _jobDepartmentFilters.Add(null);
        JobDepartmentFilter.AddItem(Loc.GetString("moff-roles-all-departments"), 0);

        foreach (var department in departments)
        {
            _jobDepartmentFilters.Add(department.ID);
            JobDepartmentFilter.AddItem(Loc.GetString(department.Name), _jobDepartmentFilters.Count - 1);
        }

        JobDepartmentFilter.SelectId(0);
    }

    /// <summary>The collapsible summary of enabled jobs; each chip turns its job back off.</summary>
    private void RefreshEnabledJobs(List<JobPrototype> jobs, Func<JobPrototype, bool> isEnabled)
    {
        var enabledJobs = jobs.Where(isEnabled).ToList();

        EnabledJobsCount.Text = enabledJobs.Count.ToString();

        if (enabledJobs.Count == 0)
        {
            EnabledJobsList.AddChild(new Label
            {
                Text = Loc.GetString("moff-roles-no-jobs-enabled"),
                FontColorOverride = MutedColor,
            });

            return;
        }

        BoxContainer? row = null;
        var column = 0;

        foreach (var job in enabledJobs)
        {
            if (column == 0)
            {
                row = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    SeparationOverride = 6,
                    Margin = new Thickness(0, 0, 0, 6),
                };

                EnabledJobsList.AddChild(row);
            }

            var chip = new Button
            {
                Text = Loc.GetString("moff-roles-enabled-job-chip", ("job", job.LocalizedName)),
                ToolTip = Loc.GetString("moff-roles-disable-job", ("job", job.LocalizedName)),
                HorizontalExpand = true,
                Margin = new Thickness(2),
            };

            chip.OnPressed += _ => SetJobEnabled(job, false);

            row!.AddChild(chip);

            column = (column + 1) % ChipColumns;
        }

        PadRow(row, column, ChipColumns);
    }

    private void AddDepartmentHeader(DepartmentPrototype department)
    {
        var header = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 4, 0, 8),
        };

        header.StyleClasses.Add("MoffProfileHeader");

        var label = new Label
        {
            Text = Loc.GetString(department.Name),
            Margin = new Thickness(6, 2),
        };

        label.StyleClasses.Add("MoffProfileTitle");

        header.AddChild(label);
        JobList.AddChild(header);
    }

    private void AddDepartmentJobs(List<JobPrototype> jobs, Func<JobPrototype, bool> isEnabled)
    {
        BoxContainer? row = null;
        var column = 0;

        foreach (var job in jobs)
        {
            if (column == 0)
            {
                row = CreateCardRow();
                JobList.AddChild(row);
            }

            var card = new MoffJobCard
            {
                HorizontalExpand = true,
                VerticalExpand = true,
            };

            card.SetName(job.LocalizedName);
            card.SetDescription(job.LocalizedDescription ?? string.Empty);
            card.SetIcon(_sprite.Frame0(_prototypeManager.Index(job.Icon).Icon));
            card.SetPreference(isEnabled(job));
            card.SetGuidebookAvailable(job.Guides is { Count: > 0 });

            card.GuidebookClicked += () =>
            {
                if (job.Guides != null)
                    OpenGuidebookRequested?.Invoke(job.Guides);
            };

            // Locked jobs stay visible so players can see they exist and read the unmet requirement.
            if (!_requirements.IsAllowed(job, _profile, out var reason))
            {
                card.SetLocked(true);

                var tooltip = new Tooltip();
                tooltip.SetMessage(reason);
                card.TooltipSupplier = _ => tooltip;

                if (isEnabled(job))
                    SetJobEnabled(job, false, refresh: false);
            }
            else
            {
                card.SetLocked(false);
            }

            card.PreferenceChanged += enabled => SetJobEnabled(job, enabled);

            var hasLoadout = _prototypeManager.HasIndex<RoleLoadoutPrototype>(LoadoutSystem.GetJobPrototype(job.ID));
            card.SetLoadoutAvailable(hasLoadout);

            if (hasLoadout)
            {
                card.LoadoutClicked += () =>
                {
                    PreviewJobChanged?.Invoke(job);
                    LoadoutRequested?.Invoke(job);
                };
            }

            row!.AddChild(card);

            column = (column + 1) % JobColumns;
        }

        PadRow(row, column, JobColumns);
    }

    private static BoxContainer CreateCardRow()
    {
        return new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 8,
            Margin = new Thickness(0, 0, 0, 8),
        };
    }

    /// <summary>Fills out a partial final row so its last item doesn't stretch across the width.</summary>
    private static void PadRow(BoxContainer? row, int column, int columns)
    {
        if (row == null || column == 0)
            return;

        for (var index = column; index < columns; index++)
        {
            row.AddChild(new Control { HorizontalExpand = true });
        }
    }

    private void SetJobEnabled(JobPrototype job, bool enabled, bool refresh = true)
    {
        if (_profile == null)
            return;

        _profile = _profile.WithJobPriority(job.ID, MoffJobPreference.ToPriority(enabled));

        NotifyProfileChanged();

        if (refresh)
            RefreshJobs();
    }

    private void NotifyProfileChanged()
    {
        if (_profile != null)
            ProfileChanged?.Invoke(_profile);
    }
}
