using Content.Client.Message;
using Content.Client.Resources;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Lobby.UI.Roles;

/// <summary>
/// One job in the roles editor: name, description, icon, a guidebook link, a loadout shortcut, and the
/// yes/no preference toggle.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MoffJobCard : PanelContainer
{
    private static readonly Color LockedModulate = Color.FromHex("#687078");

    [Dependency] private IResourceCache _resourceCache = null!;

    private bool _suppressPreferenceEvent;
    private bool _guidebookAvailable;

    public event Action? GuidebookClicked;
    public event Action? LoadoutClicked;
    public event Action<bool>? PreferenceChanged;

    public MoffJobCard()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        GuidebookButton.OnPressed += _ =>
        {
            if (_guidebookAvailable)
                GuidebookClicked?.Invoke();
        };

        LoadoutButton.OnPressed += _ => LoadoutClicked?.Invoke();

        PreferenceToggle.OnToggled += args =>
        {
            if (!_suppressPreferenceEvent)
                PreferenceChanged?.Invoke(args.Pressed);
        };

        JobDescription.OnResized += UpdateDescriptionHeight;
        OnResized += UpdateDescriptionHeight;
    }

    public void SetName(string name)
    {
        JobName.Text = name;

        // Long job titles clip badly at the default size, so step the font down instead.
        var fontSize = name.Length switch
        {
            > 24 => 12,
            > 18 => 13,
            _ => 15,
        };

        JobName.FontOverride = _resourceCache.GetFont("/Fonts/NotoSans/NotoSans-Bold.ttf", fontSize);
    }

    public void SetDescription(string description)
    {
        JobDescription.SetMarkupPermissive(description);
    }

    public void SetIcon(Texture texture)
    {
        JobIcon.Texture = texture;
    }

    public void SetPreference(bool enabled)
    {
        _suppressPreferenceEvent = true;
        PreferenceToggle.Pressed = enabled;
        _suppressPreferenceEvent = false;
    }

    /// <summary>Greys the card out and locks the toggle when the job's requirements aren't met.</summary>
    public void SetLocked(bool locked)
    {
        PreferenceToggle.Disabled = locked;
        Modulate = locked ? LockedModulate : Color.White;
    }

    public void SetGuidebookAvailable(bool available)
    {
        _guidebookAvailable = available;
        GuidebookButton.ToolTip = available
            ? Loc.GetString("humanoid-profile-editor-guidebook-button-tooltip")
            : null;
    }

    public void SetLoadoutAvailable(bool available)
    {
        LoadoutButton.Visible = available;
    }

    /// <summary>
    /// The card has to size itself around a wrapped description, so grow to fit and re-measure up the tree.
    /// </summary>
    private void UpdateDescriptionHeight()
    {
        const float minimumDescriptionHeight = 72f;
        const float descriptionPadding = 14f;
        const float headerHeight = 66f;
        const float cardPadding = 16f;
        const float separation = 7f;

        var descriptionHeight = MathF.Max(minimumDescriptionHeight, JobDescription.DesiredSize.Y + descriptionPadding);
        var requiredCardHeight = headerHeight + separation + descriptionHeight + cardPadding;

        if (MathF.Abs(MinHeight - requiredCardHeight) < 0.5f)
            return;

        DescriptionPanel.MinHeight = descriptionHeight;
        MinHeight = requiredCardHeight;

        Control? current = this;
        while (current != null)
        {
            current.InvalidateMeasure();
            current.InvalidateArrange();
            current = current.Parent;
        }
    }
}
