- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleHitman
  name: Assassin
  components:
  - type: MindRole
    subtype: role-subtype-solgov
    antagPrototype: Hitman
    exclusiveAntag: true
    subtypeColor: darkorange
  - type: HitmanRole
  - type: RoleBriefing
    briefing: hitman-briefing
