- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleHitman
  name: Hitman
  components:
  - type: MindRole
    subtype: role-subtype-hitman
    antagPrototype: Hitman
    exclusiveAntag: true
  - type: HitmanRole
  - type: RoleBriefing
    briefing: hitman-briefing
