using System.Numerics;
using Content.Client.Shuttles.Systems;
using Content.Shared._Moffstation.Shuttles.Systems;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Systems;
using Content.Shared.Timing;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Timing;

namespace Content.Client._Moffstation.Shuttles.UI;

/// <summary>
/// Replaces the upstream map screen. Pilots pick a sector from a list rather than a point on a map, so there's no
/// scanning, no FTL mode and no coordinates to click.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MoffSectorScreen : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IGameTiming _timing = default!;

    private readonly SharedFTLZoneSystem _zones;
    private readonly ShuttleSystem _shuttles;
    private readonly SharedMapSystem _maps;

    private EntityUid? _console;
    private EntityUid? _shuttleEntity;
    private EntityUid? _selected;

    private FTLState _state;
    private StartEndTime _ftlTime;

    private readonly Dictionary<EntityUid, Button> _sectors = new();
    private readonly List<EntityUid> _eligible = new();

    public event Action<EntityUid>? RequestViewSector;
    public event Action<EntityUid>? RequestFTLSector;
    public event Action? RequestExitSector;

    public MoffSectorScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _zones = _entManager.System<SharedFTLZoneSystem>();
        _shuttles = _entManager.System<ShuttleSystem>();
        _maps = _entManager.System<SharedMapSystem>();

        FTLButton.OnPressed += _ =>
        {
            if (_selected is { } sector)
                RequestFTLSector?.Invoke(sector);
        };

        ExitSectorButton.OnPressed += _ => RequestExitSector?.Invoke();
    }

    public void SetConsole(EntityUid? console)
    {
        _console = console;
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttleEntity = shuttle;
        SectorRadar.SetShuttle(shuttle);
    }

    public void SetMap(MapId mapId, Vector2 offset)
    {
        SectorRadar.SetMap(mapId, offset);
        SectorRadar.Offset = offset;
    }

    /// <summary>
    /// Opens on whichever sector the shuttle is currently in.
    /// </summary>
    public void Startup()
    {
        if (_shuttleEntity is not { } shuttle ||
            !_entManager.TryGetComponent<TransformComponent>(shuttle, out var xform) ||
            xform.MapUid is not { } mapUid)
        {
            return;
        }

        SelectSector(mapUid);
    }

    public void UpdateState(ShuttleMapInterfaceState state)
    {
        _state = state.FTLState;
        _ftlTime = state.FTLTime;

        FTLStateLabel.Text = Loc.GetString($"shuttle-console-ftl-state-{_state}");
        ExitSectorButton.Visible = state.CanExitSector;

        RebuildSectors();
        UpdateFTLAvailability();
    }

    /// <summary>
    /// The FTL button is gated on the same <see cref="SharedFTLZoneSystem.InZone"/> the server refuses on, so the
    /// reason shows up before the pilot presses anything.
    /// </summary>
    private void UpdateFTLAvailability()
    {
        var ready = _state == FTLState.Available;
        var inZone = _shuttleEntity is not { } shuttle || _zones.InZone(shuttle);

        FTLButton.Disabled = !ready || !inZone || _selected == null;
        ExitSectorButton.Disabled = !ready || !inZone;

        FTLReasonLabel.Visible = ready && !inZone;
        FTLReasonLabel.Text = Loc.GetString("shuttle-console-ftl-zone");
    }

    private void RebuildSectors()
    {
        _eligible.Clear();

        var query = _entManager.AllEntityQueryEnumerator<MapComponent, MetaDataComponent>();
        while (query.MoveNext(out var uid, out var map, out _))
        {
            // Handles the whitelist and the coordinate-disk requirement for expedition maps for us.
            if (_shuttleEntity is not { } shuttle ||
                _console is not { } console ||
                !_shuttles.CanFTLTo(shuttle, map.MapId, console))
            {
                continue;
            }

            _eligible.Add(uid);
        }

        // Only tear the list down when the set actually changes, otherwise selection flickers every state update.
        if (_eligible.Count == _sectors.Count && _eligible.TrueForAll(_sectors.ContainsKey))
            return;

        SectorList.RemoveAllChildren();
        _sectors.Clear();

        foreach (var uid in _eligible)
        {
            var name = _entManager.GetComponent<MetaDataComponent>(uid).EntityName;

            if (string.IsNullOrEmpty(name))
                name = Loc.GetString("shuttle-console-unknown");

            var button = new Button
            {
                Text = name,
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = _selected == uid,
            };

            var sector = uid;
            button.OnPressed += _ => SelectSector(sector);

            SectorList.AddChild(button);
            _sectors.Add(uid, button);
        }

        // The selected sector may have just vanished from the list.
        if (_selected is { } selected && !_sectors.ContainsKey(selected))
            _selected = null;
    }

    private void SelectSector(EntityUid mapUid)
    {
        _selected = mapUid;

        foreach (var (uid, button) in _sectors)
        {
            button.Pressed = uid == mapUid;
        }

        // Sectors the player isn't in are outside their PVS, so ask the server to push this one's grids over.
        RequestViewSector?.Invoke(mapUid);

        if (_entManager.TryGetComponent<MapComponent>(mapUid, out var map))
            SectorRadar.FocusSector(map.MapId);

        UpdateFTLAvailability();
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        var progress = _ftlTime.ProgressAt(_timing.CurTime);
        FTLBar.Value = float.IsFinite(progress) ? progress : 1f;
    }
}
