using System.Numerics;
using Content.Client._Moffstation.Shuttles.Systems;
using Content.Client.Shuttles.Systems;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.Systems;
using Content.Shared.Shuttles.UI.MapObjects;
using Content.Shared.Timing;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Timing;

namespace Content.Client._Moffstation.Shuttles.UI;

/// <summary>
/// Shuttle console map screen: previews sectors the shuttle can FTL to and warps to the selected one.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MoffMapScreen : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IGameTiming _timing = default!;

    private static readonly TimeSpan RefreshInterval = TimeSpan.FromSeconds(0.5);

    private readonly HyperspaceRiftSystem _rifts;
    private readonly SharedMapSystem _maps;
    private readonly ShuttleSystem _shuttles;
    private readonly SharedTransformSystem _xformSystem;

    private EntityUid? _console;
    private EntityUid? _shuttleEntity;

    private FTLState _state;
    private StartEndTime _ftlTime;

    private List<ShuttleBeaconObject> _beacons = new();
    private List<ShuttleExclusionObject> _exclusions = new();

    private readonly StyleBoxFlat _ftlStyle;

    private readonly Dictionary<MapId, List<IMapObject>> _mapObjects = new();
    private readonly List<IMapObject> _viewedObjects = new();
    private readonly Dictionary<EntityUid, Button> _sectorButtons = new();
    private readonly List<(EntityUid Map, string Name)> _sectors = new();

    private EntityUid? _selectedSector;
    private TimeSpan _nextRefresh;

    public event Action<NetEntity>? RequestSectorFTL;

    public MoffMapScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _rifts = _entManager.System<HyperspaceRiftSystem>();
        _maps = _entManager.System<SharedMapSystem>();
        _shuttles = _entManager.System<ShuttleSystem>();
        _xformSystem = _entManager.System<SharedTransformSystem>();

        _ftlStyle = new StyleBoxFlat(Color.LimeGreen);
        FTLBar.ForegroundStyleBoxOverride = _ftlStyle;

        WarpButton.OnPressed += _ =>
        {
            if (_selectedSector is { } sector)
                RequestSectorFTL?.Invoke(_entManager.GetNetEntity(sector));
        };
    }

    public void SetConsole(EntityUid? console)
    {
        _console = console;
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttleEntity = shuttle;
        MapRadar.SetShuttle(shuttle);
    }

    public void SetMap(MapId mapId, Vector2 position)
    {
        MapRadar.SetMap(mapId, position);
        MapRadar.Offset = position;
    }

    /// <summary>
    /// Called when the screen is opened: views the shuttle's own map.
    /// </summary>
    public void Startup()
    {
        if (!_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform))
            return;

        _selectedSector = shuttleXform.MapUid;
        SetMap(shuttleXform.MapID, _maps.GetGridPosition((_shuttleEntity.Value, null, shuttleXform)));
        RefreshSectors();
        RebuildMapObjects();
    }

    public void UpdateState(ShuttleMapInterfaceState state)
    {
        _beacons = state.Destinations;
        _exclusions = state.Exclusions;
        _state = state.FTLState;
        _ftlTime = state.FTLTime;
        MapFTLState.Text = Loc.GetString($"shuttle-console-ftl-state-{_state.ToString()}");
        MapRadar.InFtl = _state is not (FTLState.Available or FTLState.Cooldown);

        _ftlStyle.BackgroundColor = _state switch
        {
            FTLState.Available => Color.FromHex("#80C71F"),
            FTLState.Starting => Color.FromHex("#169C9C"),
            FTLState.Travelling => Color.FromHex("#8932B8"),
            FTLState.Arriving => Color.FromHex("#F9801D"),
            _ => Color.FromHex("#B02E26"),
        };

        // Follow the shuttle to wherever it arrived.
        if (_state == FTLState.Cooldown &&
            _entManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform))
        {
            _selectedSector = shuttleXform.MapUid;
            MapRadar.SetMap(shuttleXform.MapID, _maps.GetGridPosition(_shuttleEntity.Value), recentering: true);
        }

        RefreshSectors();
        RebuildMapObjects();
    }

    /// <summary>
    /// Rebuilds the sector list if the reachable maps changed, then updates which can be warped to.
    /// </summary>
    private void RefreshSectors()
    {
        _sectors.Clear();

        if (_shuttleEntity != null && _console != null &&
            _entManager.TryGetComponent(_shuttleEntity, out TransformComponent? shuttleXform))
        {
            foreach (var map in _entManager.AllEntityQueryEnumerator<MapComponent, MetaDataComponent>())
            {
                if (map.Owner != shuttleXform.MapUid &&
                    !_shuttles.CanFTLTo(_shuttleEntity.Value, map.Comp1.MapId, _console.Value))
                {
                    continue;
                }

                var name = string.IsNullOrEmpty(map.Comp2.EntityName)
                    ? Loc.GetString("shuttle-console-unknown")
                    : map.Comp2.EntityName;

                if (map.Owner == shuttleXform.MapUid)
                    name = Loc.GetString("shuttle-console-sector-current", ("name", name));

                _sectors.Add((map.Owner, name));
            }
        }

        _sectors.Sort((x, y) => string.Compare(x.Name, y.Name, StringComparison.CurrentCultureIgnoreCase));

        if (!SectorsMatchButtons())
            RebuildSectorButtons();

        SyncButtonState();
    }

    private bool SectorsMatchButtons()
    {
        if (_sectors.Count != _sectorButtons.Count)
            return false;

        foreach (var (map, name) in _sectors)
        {
            if (!_sectorButtons.TryGetValue(map, out var button) || button.Text != name)
                return false;
        }

        return true;
    }

    private void RebuildSectorButtons()
    {
        SectorList.RemoveAllChildren();
        _sectorButtons.Clear();

        var group = new ButtonGroup();

        foreach (var (map, name) in _sectors)
        {
            var button = new Button
            {
                Text = name,
                ToggleMode = true,
                Group = group,
                HorizontalExpand = true,
                ClipText = true,
                Pressed = map == _selectedSector,
            };

            button.OnPressed += _ => SelectSector(map);

            _sectorButtons.Add(map, button);
            SectorList.AddChild(button);
        }

        NoSectorsLabel.Visible = _sectors.Count <= 1;
    }

    private void SelectSector(EntityUid map)
    {
        if (!_entManager.TryGetComponent(map, out MapComponent? mapComp))
            return;

        _selectedSector = map;

        if (_rifts.TryGetRiftPosition(map, out var riftPos))
            SetMap(mapComp.MapId, riftPos.Value);
        else if (_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? xform) && xform.MapUid == map)
            SetMap(mapComp.MapId, _maps.GetGridPosition(_shuttleEntity.Value));
        else
            SetMap(mapComp.MapId, Vector2.Zero);

        RebuildMapObjects();
        SyncButtonState();
    }

    /// <summary>
    /// The only place sector and warp buttons are enabled or disabled.
    /// </summary>
    private void SyncButtonState()
    {
        var shuttleMap = _entManager.GetComponentOrNull<TransformComponent>(_shuttleEntity)?.MapUid;
        var inRift = _shuttleEntity == null || _rifts.CanDepart(_shuttleEntity.Value);
        var canWarp = _state == FTLState.Available && inRift;

        var reason = canWarp ? null : Loc.GetString(inRift ? "shuttle-console-warp-unavailable" : "shuttle-console-outside-rift");

        RiftStatus.Visible = !inRift;

        foreach (var (map, button) in _sectorButtons)
        {
            button.Pressed = map == _selectedSector;
            button.Disabled = map != shuttleMap && !canWarp;
            button.ToolTip = button.Disabled ? reason : null;
        }

        WarpButton.Disabled = !canWarp || _selectedSector == null || _selectedSector == shuttleMap;
        WarpButton.ToolTip = reason;
    }

    /// <summary>
    /// Collects the grids, beacons and exclusions on the viewed map for drawing.
    /// </summary>
    private void RebuildMapObjects()
    {
        _mapObjects.Clear();
        _viewedObjects.Clear();

        var mapId = MapRadar.ViewingMap;

        if (mapId == MapId.Nullspace)
            return;

        var mapUid = _maps.GetMapOrInvalid(mapId);
        var objects = _viewedObjects;

        foreach (var grid in _maps.GetAllGrids(mapId))
        {
            _entManager.TryGetComponent(grid.Owner, out IFFComponent? iffComp);

            var gridObj = new GridMapObject
            {
                Name = _entManager.GetComponent<MetaDataComponent>(grid.Owner).EntityName,
                Entity = grid.Owner,
                HideButton = iffComp != null && (iffComp.Flags & IFFFlags.HideLabel) != 0x0,
            };

            if (grid.Owner == _shuttleEntity ||
                !_shuttles.IsBeaconMap(mapUid) && (iffComp == null || (iffComp.Flags & IFFFlags.Hide) == 0x0))
            {
                objects.Add(gridObj);
            }
        }

        foreach (var (exclusion, _) in _shuttles.GetExclusions(mapId, _exclusions))
        {
            objects.Add(exclusion);
        }

        foreach (var (beacon, _) in _shuttles.GetBeacons(mapId, _beacons))
        {
            objects.Add(beacon);
        }

        _mapObjects[mapId] = objects;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var curTime = _timing.CurTime;
        var progress = _ftlTime.ProgressAt(curTime);
        FTLBar.Value = float.IsFinite(progress) ? progress : 1;

        if (!Visible || curTime < _nextRefresh)
            return;

        // The shuttle moving into or out of the rift and new grids appearing don't send a state update.
        _nextRefresh = curTime + RefreshInterval;
        SyncButtonState();
        RebuildMapObjects();
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        MapRadar.SetMapObjects(_mapObjects);
        base.Draw(handle);
    }
}
