using System.Numerics;
using Content.Client.Shuttles.Systems;
using Content.Client.Shuttles.UI;
using Content.Shared._Moffstation.Shuttles.Systems;
using Content.Shared.Shuttles.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;

namespace Content.Client._Moffstation.Shuttles.UI;

/// <summary>
/// Radar view of a single sector. Read-only - picking where to arrive isn't the pilot's call, so there's no FTL mode
/// or click-to-jump here.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MoffSectorMapControl : BaseShuttleControl
{
    private readonly SharedFTLZoneSystem _zones;
    private readonly ShuttleSystem _shuttles;
    private readonly SharedTransformSystem _xform;

    public MapId ViewingMap = MapId.Nullspace;

    private EntityUid? _shuttleEntity;

    // Not readonly - FindGridsIntersecting takes it by ref.
    private List<Entity<MapGridComponent>> _grids = new();

    protected override bool Draggable => true;

    // Wide zoom range: a sector's station and its zone can be hundreds of units apart, and the screen has to fit both.
    public MoffSectorMapControl() : base(64f, 4096f, 512f)
    {
        RobustXamlLoader.Load(this);

        _zones = EntManager.System<SharedFTLZoneSystem>();
        _shuttles = EntManager.System<ShuttleSystem>();
        _xform = EntManager.System<SharedTransformSystem>();
    }

    public void SetMap(MapId mapId, Vector2 offset, bool recentering = false)
    {
        ViewingMap = mapId;
        TargetOffset = offset;
        Recentering = recentering;
    }

    public void SetShuttle(EntityUid? entity)
    {
        _shuttleEntity = entity;
    }

    /// <summary>
    /// Points the view at a sector, centred on its station and zoomed out far enough to take in the whole thing.
    /// </summary>
    public void FocusSector(MapId mapId)
    {
        var centre = GetSectorCentre(mapId);

        ViewingMap = mapId;
        TargetOffset = centre;
        Offset = centre;
        Recentering = false;
        ActualRadarRange = Math.Clamp(GetFitRange(mapId, centre), WorldMinRange, WorldMaxRange);
    }

    /// <summary>
    /// The sector's station, or the map origin if it hasn't got one. Deliberately not the zone or the shuttle: the
    /// station is the landmark a pilot orients by, and it keeps the view still as the shuttle moves.
    /// </summary>
    private Vector2 GetSectorCentre(MapId mapId)
    {
        return _zones.GetLargestGrid(mapId) is { } station ? Maps.GetGridPosition(station.Owner) : Vector2.Zero;
    }

    /// <summary>
    /// How far out the view has to be to fit this sector's grids and its zone.
    /// </summary>
    private float GetFitRange(MapId mapId, Vector2 centre)
    {
        var range = 0f;

        foreach (var grid in Maps.GetAllGrids(mapId))
        {
            var gridPos = Maps.GetGridPosition(grid.Owner);
            range = MathF.Max(range, (gridPos - centre).Length() + grid.Comp.LocalAABB.Size.Length() / 2f);
        }

        if (Maps.TryGetMap(mapId, out var mapUid) && _zones.TryGetZone(mapUid.Value, out var zone))
            range = MathF.Max(range, (_xform.GetWorldPosition(zone) - centre).Length() + zone.Comp.Radius);

        // A little breathing room so nothing sits right on the edge.
        return range * 1.15f;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        DrawBacking(handle);

        if (ViewingMap == MapId.Nullspace)
        {
            DrawNoSignal(handle);
            return;
        }

        DrawRecenter();

        DrawParallaxBackground(handle, ViewingMap, Offset);
        DrawCircles(handle);

        // Unrotated, so this is just "shift by the view centre, scale to pixels, flip Y, move to the middle".
        var worldToView = Matrix3x2.CreateTranslation(-Offset)
                          * Matrix3x2.CreateScale(new Vector2(MinimapScale, -MinimapScale))
                          * Matrix3x2.CreateTranslation(MidPointVector);

        DrawZone(handle, worldToView);
        DrawGrids(handle, worldToView);
    }

    private void DrawZone(DrawingHandleScreen handle, Matrix3x2 worldToView)
    {
        if (!Maps.TryGetMap(ViewingMap, out var mapUid) || !_zones.TryGetZone(mapUid.Value, out var zone))
            return;

        var centre = Vector2.Transform(_xform.GetWorldPosition(zone), worldToView);
        var radius = zone.Comp.Radius * MinimapScale;

        handle.DrawCircle(centre, radius, zone.Comp.Color.WithAlpha(0.05f));
        handle.DrawCircle(centre, radius, zone.Comp.Color, filled: false);
    }

    /// <summary>
    /// Real hull outlines rather than the diamonds the upstream map screen draws for distant maps.
    /// </summary>
    private void DrawGrids(DrawingHandleScreen handle, Matrix3x2 worldToView)
    {
        // Culled to the viewport: DrawGrid transforms every vertex of every grid it's handed, so an unfiltered
        // GetAllGrids would chew through whole stations that are panned off screen.
        _grids.Clear();
        Maps.FindGridsIntersecting(ViewingMap,
            new Box2(Offset - WorldRangeVector, Offset + WorldRangeVector),
            ref _grids,
            approx: true,
            includeMap: false);

        foreach (var grid in _grids)
        {
            var self = _shuttleEntity == grid.Owner;
            EntManager.TryGetComponent(grid.Owner, out IFFComponent? iff);

            // Same filter the nav radar uses, so debris and IFF-hidden grids don't clutter the sector view.
            if (!self && !_shuttles.CanDraw(grid.Owner, iffComp: iff))
                continue;

            var color = _shuttles.GetIFFColor(grid.Owner, self, iff);

            DrawGrid(handle, _xform.GetWorldMatrix(grid.Owner) * worldToView, grid, color);

            if (iff != null && (iff.Flags & IFFFlags.HideLabel) != 0x0)
                continue;

            var label = _shuttles.GetIFFLabel(grid.Owner, self, iff);

            if (string.IsNullOrEmpty(label))
                continue;

            var labelPos = Vector2.Transform(Maps.GetGridPosition(grid.Owner), worldToView);
            var size = handle.GetDimensions(Font, label, 1f);

            handle.DrawString(Font, labelPos - new Vector2(size.X / 2f, 0f), label, Color.FromSrgb(color));
        }
    }
}
