using Content.Shared.Shuttles.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Shuttles.UI;

/// <summary>
/// Terminal-style readout of a shuttle's IFF name with a preview of its hull.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ShuttleIFFDisplay : PanelContainer
{
    [Dependency] private IEntityManager _entManager = default!;

    private readonly SharedShuttleSystem _shuttles;

    public ShuttleIFFDisplay()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _shuttles = _entManager.System<SharedShuttleSystem>();
    }

    public void SetConsole(EntityUid? console)
    {
        Preview.SetConsole(console);
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        Preview.SetShuttle(shuttle);

        IFFLabel.Text = shuttle != null && _entManager.EntityExists(shuttle)
            ? _shuttles.GetIFFLabel(shuttle.Value, self: true)
            : Loc.GetString("shuttle-console-unknown");
    }
}
